### ISSUE TITLE
What is the designed procedure to publish the views?

### ISSUE THREAD

**Issue by nestormata** [artkonekt/appshell#1]
Hi,

I'm not sure if this is per design, but in the documentation is mentioned that we should versioning the views files under the vendor directory.
If this is the intended option I think is a little messy, the whole point of vendor is to be able to not version it, but instead pulled when necessary, trying to versioning files there may be a conflict when updating versions.
I think the best option would be to publish the views locally using the standard Laravel functionality and then customize them there.

Note: This module seems pretty promising, thanks for the hard work.

**Comment by fulopattila122** [comment]
Hello Nestor,

thanks for opening this issue.
I'm not sure if I completely understand your concern.
Could you please point me to the point where this:
> documentation is mentioned that we should versioning the views files under the vendor directory.

can be read?

Cheers

**Comment by nestormata** [comment]
Hi,
I've been getting familiar with your project in these last few days. I like it.

Here is what I mean:
In the documentation, under "Configure PhpStorm For Properly Editing Sources In Vendor" you are telling us to edit files under the /vendor/ directory to customize the views.

In general terms with Composer and in specific terms in Laravel this is asked to be avoided.
As a rule of thumb, you should not touch files under /vendor/ because those files will be overwritten with any update or install, so this is discouraged.

There is a way thought, that you can set the files to be "published" to the local resources/views/vendor directory and if Laravel finds that the file requested is indeed there it will use that version instead of the one under /vendor/ .

So, instead, I think you should set the files to be published and document the step that publishes them and indicate where to find them.

Best regards,
Nestor

**Comment by fulopattila122** [comment]
Ah OK, now I see it. That was a note actually for ourselves, for developing AppShell itself, not the application with AppShell. Will remove it in the next hour.

**Comment by nestormata** [comment]
Oh ok, I see.
What I did in my case, for now, was to copy over the files manually to ./resources/views/vendor/ and all worked just fine and I was able to customize them.

**Comment by fulopattila122** [comment]
Yes, that's perfectly fine. I have plans to make the whole thing themeable, but have no ETA for that yet.
Hopefully I'll be able to finish the settings/preferences feature this weekend. Keep checking the repo ;)
