### ISSUE TITLE
Docs mix code says 'app.js' but file referenced is 'apphell.js' 

### ISSUE THREAD

**Issue by andreud** [artkonekt/appshell#12]
In the Admin Panel doc page: https://artkonekt.github.io/appshell/#/admin-panel?id=appshell-as-main-app-ui
It says to add this line:
`mix.js(..., 'public/js/app.js')`
But the file referenced in the provided layout is `appshell.js`, not `app.js`

**Comment by fulopattila122** [comment]
Thanks for the feedback, I'll fix this section by adding more details.
