### ISSUE TITLE
Error after installing vanilo/frameworks in appshell

### ISSUE THREAD

**Issue by j-dohnalek** [artkonekt/appshell#14]
Using version ^1.4 for konekt/appshell

> @php artisan package:discover
PHP Warning:  Uncaught ErrorException: require(/vendor/konekt/appshell/src/resources/routes/web.php): failed to open stream: No such file or directory in /vendor/laravel/framework/src/Illuminate/Routing/RouteFileRegistrar.php:35

The actual file `web.php` does not exists looking through the package.

Any advice please?

**Comment by fulopattila122** [comment]
Is it a fresh install or an existing app?

**Comment by j-dohnalek** [comment]
existing app

**Comment by fulopattila122** [comment]
Can you check the content of concord.php in the config folder please?

**Comment by j-dohnalek** [comment]
hmm, can I assume that the `web` should be pointing to `acl` and `nonacl` in `files`?

```php
'routes' => [
     'prefix'     => 'dashboard',
    'middleware' => ['web', 'auth', 'acl'],
    'files'      => ['web'],
    'as' => 'appshell.'
],
```

**Comment by j-dohnalek** [comment]
the answer is yes, actually. It solved the problem thanks

**Comment by fulopattila122** [comment]
Just two more questions:
- Did you update Vanilo 0.5 -> 1.0?
- What Laravel version is the application at?

thx!

**Comment by j-dohnalek** [comment]
I did upgrade 0.5 to 1.0
And I have version 5.8
