### ISSUE TITLE
Overwrite APPSHELL Layouts in a custom application

### ISSUE THREAD

**Issue by marcelopalacioabreu** [artkonekt/appshell#19]
I'm using Vanilo and i can overwrite layout files to translate or add fields by copying it to views/vendor/vanilo directory. How i can do this with APPSHELL?

**Comment by fulopattila122** [comment]
Just put them in the `resources/view/vendor/appshell` directory.
For available views to override refer to: https://github.com/artkonekt/appshell/tree/1.8/src/resources/views

**Comment by fulopattila122** [comment]
Oh, and btw we're working on AppShell v2 where theming and customization will have a much better support.
Vanilo 2.0 will have AppShell 2.0 under the hood

**Comment by marcelopalacioabreu** [comment]
Oh, Thank you! It worked perfectly.

**Comment by marcelopalacioabreu** [comment]
I'm closing the issue.
