### ISSUE TITLE
Remove davejamesmiller/laravel-breadcrumbs dependency

### ISSUE THREAD

**Issue by j-dohnalek** [artkonekt/appshell#23]
The `davejamesmiller/laravel-breadcrumbs` project have been discontinued, can you please consider to https://github.com/diglactic/laravel-breadcrumbs?

**Comment by fulopattila122** [comment]
Hi, yes it's been done already see #22 
It's in the 2.0 version. Would you need a backport in the 1.x series?

**Comment by j-dohnalek** [comment]
Oh, cool. No we do not need one thank you

**Comment by fulopattila122** [comment]
Just a note, AppShell 2 has been changed a lot under the hood, if you're upgrading an existing project, I recommend the [upgrade guide](https://konekt.dev/appshell/2.x/upgrade).

**Comment by j-dohnalek** [comment]
Ok, thanks
